name: Demo Workflow
on:
  workflow_dispatch:
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run Action 1
        uses: SriGanesh373/gh_cicd_practise/action1
      - name: Run Action 2
        uses: SriGanesh373/gh_cicd_practise/action2
